language: python
python: "3.5"

notifications:      # 邮箱通知
  email: false

sudo: false #有定制化开发环境需要，默认false，不开启容器，编译效率高
#sudo: required

before_install: 
  - pip install -r requirements.txt #加sudo默认系统环境里的python，使用虚拟环境需加-E参数 
  - pip install codecov 
  - pip install coverage
#- sudo apt-get install -y libxml2-dev   #-y: always answer yes

# set true to jump over one process
# if one failed, the later won't be executed
install: true 

# if one failed, the later will still be executed
script: 
  - coverage run decrypt.py music

after_success:
  - codecov #运行codecov

#after_failure
#before_deploy
#deploy
#after_deploy

